### ISSUE TITLE
Blank page when clicking the access button

### ISSUE THREAD

**Issue by hbbk** [udima-university/moodle-mod_jitsi#41] opened 2020-05-04 09:22 UTC
hi I'm using the latest jitsi plugin v2.4 2020042900 and the only thing I can get is a blanck page with
my moodle 3.4.2+ when clicking the access button (Jitsi - Click the button to access ...)

I have another test server with 3.5.2+ installed and exactly the same jitsi config, server and plugin and that works perfectly there (?). 

any idea please ?

I'v got the folowing error with google chrome inspecter
```
external_api.js:1 Unrecognized feature: 'display-capture'.
_createIFrame @ external_api.js:1
external_api.js:1 Uncaught TypeError: Cannot read property 'appendChild' of null
    at $._createIFrame (external_api.js:1)
    at new $ (external_api.js:1)
    at session.php:282
DevTools failed to load SourceMap: Could not load content for https://jitsi.xxx/external_api.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by SergioComeron** [comment] 2020-05-04 17:13
Hi @hbbk 
what theme are you using with your moodle?

**Comment by hbbk** [comment] 2020-05-05 07:12
the standard theme with some very few css adds nothing fancy... (they are the same on both servers)

**Comment by pieterjanheyse** [comment] 2020-05-28 08:12
We are seeing the exact same issue with a small percentage of our users across multiple computers and browsers, but with the same public ip address. Is there a parameter (public ip address for example) in common here? 

When the people use meet.jit.si with the appropriate roomname, things work fine. 

Moodle 3.7.2+ (Build: 20191004)
Jitsi v2.5 2020050700

Also using the standard theme. 

Is there anything I can do to debug further, I have a user who I can contact to help me out.

**Comment by JohnCarlos007** [comment] 2020-10-27 02:16
Were experiencing a similar problem with the plugin.

Some users are able to experience this while others do not. We had 30 users using a multiple Jitsi activity in several courses, with two persons each Jitsi activity. We also use the theme "Trema" in Moodle.

I dont know if this helps but will expect for a fix soon.  

Moodle 3.9.2
Jitsi v2.8.2

**Comment by bryanasdev000** [comment] 2020-11-14 09:50
This problem can be on the Jitsi side, since this plugin only calls it.

The NGINX (jitsi-meet) and Jicofo logs can be useful in this case, to perform a deeper analysis.

**Comment by moha-rk** [comment] 2021-11-29 12:41
Hello. A friend of mine had the same problem, and after debugging it to her, I found out that the problem was a char in her username that was breaking the call to the API. Can you tell me your name on the moodle platform so I can confirm it's the same issue, and if so, try to link a fix to it

**Comment by SergioComeron** [comment] 2021-11-29 13:06
Hi @moha-rk 
what was the character?

**Comment by moha-rk** [comment] 2021-11-29 13:34
@SergioComeron It was a ' (apostrophe) that wasn't added to the API call as \' , but simply as '. That was ending the string too soon, leaving another single ' at the end, breaking the call

**Comment by SergioComeron** [comment] 2021-11-30 08:54
I'm trying to reproduce the problem but I cannot add a user that has an apostrophe in the username. How did you manage to have a user with username that has an apostrophe?
<img width="1436" alt="Captura de pantalla 2021-11-30 a las 9 51 43" src="https://user-images.githubusercontent.com/14803178/144015637-22a419b7-aa95-40b7-8ad6-7c4ff7a44bd1.png">

**Comment by ivankazzzz** [comment] 2022-05-30 12:36
Hello, is there a fix for this ?
i also facing this issue

**Comment by ivankazzzz** [comment] 2022-05-31 00:29
Hi
Sorry for late confirming
its been fixed now

idk whats goin wrong, it work normally ( September 2021) at first then suddenly it comes blank ( May 2022 )

i use `Jitsi v3.1.1` then i tryin updatin to latest 
it works well

my guess its the jitsi side problem

**Comment by SergioComeron** [comment] 2022-05-31 08:08
ok, Thanks for the update

**Closed by SergioComeron** 2022-05-31 08:08 UTC
