### ISSUE TITLE
get_string is not escaped in lib.php

### ISSUE THREAD

**Issue by hrenard** [udima-university/moodle-mod_jitsi#114] opened 2023-01-06 10:24 UTC
Hey !

In the French translation, we can have `'` character. For example : `the record` => `l'enregistrement`. So, it can break the code, like here : https://github.com/udima-university/moodle-mod_jitsi/blob/12b777bcb09b5ab8a0055e8733a0a21230944803/lib.php#L636-L637

Might be worth escaping every `get_string` that is injected in this way.

**Comment by SergioComeron** [comment] 2023-01-11 09:50
Hi @hrenard 
I can't reproduce the problem. Can you give me the steps to reproduce it?

**Comment by niconicoDT** [comment] 2023-01-13 15:24
Hi @SergioComeron,

On our moodle 3.11 in French, with the Fordson theme, when I want to access a jitsi activity in a course, I get a white screen. 
This is the error message I find in the firefox console :

_Uncaught SyntaxError: unexpected token: identifier session.php:737:608_

And this is what I see in the debugger :

`document.getElementById('state').innerHTML =       '<div class="alert alert-primary" role="alert"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:"><path d="M0 5a2 2 0 0 1 2-2h7.5a2 2 0 0 1 1.983 1.738l3.11-1.382A1 1 0 0 1 16 4.269v7.462a1 1 0 0 1-1.406.913l-3.111-1.382A2 2 0 0 1 9.5 13H2a2 2 0 0 1-2-2V5zm11.5 5.175 3.5 1.556V4.269l-3.5 1.556v4.35zM2 4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h7.5a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H2z"/></svg> La session est en cours d'enregistrement</div>';    } else if (event['on'] == false){`

It seems that `l’enregistrement` breaks the code because of the  `’` character

But as soon as I switch to english jitsi works.

In other word, for the same jitsi activity this url works :

https://moodle.platform/mod/jitsi/view.php?id=XYZ&lang=en

but not this one :

https://moodle.platform/mod/jitsi/view.php?id=XYZ&lang=fr

Hope it can help

**Comment by SergioComeron** [comment] 2023-01-13 15:58
It is possible that the problem is due to the Fordson theme. I've been testing with boost and I didn't see any errors. I'm going to download Fordson to test it and I'll tell you.
Thanks!

**Comment by JacquesLG** [comment] 2023-01-23 19:23
Hi @SergioComeron 

I am having the same issue with this on the Boost theme.

**Comment by JacquesLG** [comment] 2023-01-23 19:37
Hello again,

I applied a fix for this with #116 

I tested it on my server with boost template and french language and it works fine 👍

**Comment by SergioComeron** [comment] 2023-01-25 12:45
Thank you all, when I was doing my tests I was forgetting to change the moodle language to French. And so it couldn't reproduce the error.
The patch contributed by @JacquesLG  fixes it. It will be in the next version.

**Closed by SergioComeron** 2023-01-25 12:45 UTC
